name: Lab 7

# Trigger the pipeline only on push (or pull request) to a "test" branch
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # Run backend tests in the pipeline AND read GitHub secrets for the environmentTest
      - name: Run backend tests
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew test

      # Run the Jacoco report in the pipeline
      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport

      # Optional: Upload the JaCoCo report as an artifact so you can download it from GitHub Actions
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test/html/